# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pasciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('dueño', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.IntegerField()),
                ('pascientes', models.ManyToManyField(through='veterinarias.Consulta', to='veterinarias.Pasciente')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='Pasciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarias.Pasciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinarias.Veterinario'),
        ),
    ]
