# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fecha_consulta',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
