# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarias', '0002_consulta_fecha_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='fecha_consulta',
        ),
        migrations.AddField(
            model_name='veterinario',
            name='fecha_consulta',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
